/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "oss.h"

void FuelTypes_Initialize(FuelTypes* pVal)
{
	(void)pVal;


	(*(pVal)) = solid;
}

flag FuelTypes_IsConstraintValid(const FuelTypes* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
	
    ret = ((((((*(pVal)) == solid)) || (((*(pVal)) == liquid)))) || (((*(pVal)) == gas)));
    *pErrCode = ret ? 0 :  ERR_FUELTYPES; 

	return ret;
}



void SpeedParameters_Initialize(SpeedParameters* pVal)
{
	(void)pVal;


	/*set mph*/
	pVal->kind = mph_PRESENT;
	pVal->u.mph = 0;
}

flag SpeedParameters_IsConstraintValid(const SpeedParameters* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
	
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}



void Rocket_name_Initialize(Rocket_name val)
{
	(void)val;


	memset(val, 0x0, 13);

}
void Rocket_message_Initialize(Rocket_message val)
{
	(void)val;


	memset(val, 0x0, 20);

}
void Rocket_payload_elem_Initialize(Rocket_payload_elem val)
{
	(void)val;


	memset(val, 0x0, 14);

}
void Rocket_payload_Initialize(Rocket_payload* pVal)
{
	(void)pVal;

    int i1;

	i1 = 0;
	while (i1< 7) {
	    Rocket_payload_elem_Initialize(pVal->arr[i1]);
	    i1 = i1 + 1;
	}
	pVal->nCount = 1;
}
void Rocket_Initialize(Rocket* pVal)
{
	(void)pVal;



	/*set xrange */
	pVal->xrange = 0;
	/*set name */
	Rocket_name_Initialize(pVal->name);
	/*set message */
	Rocket_message_Initialize(pVal->message);
	/*set fuel */
	FuelTypes_Initialize((&(pVal->fuel)));
	/*set speed */
	pVal->exist.speed = 1;
	SpeedParameters_Initialize((&(pVal->speed)));
	/*set payload */
	Rocket_payload_Initialize((&(pVal->payload)));
}

flag Rocket_IsConstraintValid(const Rocket* pVal, int* pErrCode)
{
    flag ret = TRUE;
    int i1;
	(void)pVal;
	
    ret = ((1 <= strlen(pVal->name)) && (strlen(pVal->name) <= 12));
    *pErrCode = ret ? 0 :  ERR_ROCKET_NAME; 
    if (ret) {
        ret = ((1 <= strlen(pVal->message)) && (strlen(pVal->message) <= 19));
        *pErrCode = ret ? 0 :  ERR_ROCKET_MESSAGE; 
        if (ret) {
            ret = FuelTypes_IsConstraintValid((&(pVal->fuel)), pErrCode);
            if (ret) {
                if (pVal->exist.speed) {
                	ret = SpeedParameters_IsConstraintValid((&(pVal->speed)), pErrCode);
                }
                if (ret) {
                    ret = ((1 <= pVal->payload.nCount) && (pVal->payload.nCount <= 7));
                    *pErrCode = ret ? 0 :  ERR_ROCKET_PAYLOAD; 
                    if (ret) {
                        for(i1 = 0; ret && i1 < pVal->payload.nCount; i1++) 
                        {
                        	ret = ((1 <= strlen(pVal->payload.arr[i1])) && (strlen(pVal->payload.arr[i1]) <= 13));
                        	*pErrCode = ret ? 0 :  ERR_ROCKET_PAYLOAD_ELM; 
                        }
                    }
                }
            }
        }
    }

	return ret;
}



void Coordinate_Initialize(Coordinate* pVal)
{
	(void)pVal;



	/*set x */
	pVal->x = 0.00000000000000000000E+000;
	/*set y */
	pVal->y = 0.00000000000000000000E+000;
}

flag Coordinate_IsConstraintValid(const Coordinate* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
	
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}



void ArmoryInfo_Initialize(ArmoryInfo* pVal)
{
	(void)pVal;



	/*set isExist */
	pVal->isExist = FALSE;
	/*set xcoordinate */
	pVal->exist.xcoordinate = 1;
	Coordinate_Initialize((&(pVal->xcoordinate)));
}

flag ArmoryInfo_IsConstraintValid(const ArmoryInfo* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
	
    if (pVal->exist.xcoordinate) {
    	ret = Coordinate_IsConstraintValid((&(pVal->xcoordinate)), pErrCode);
    }

	return ret;
}



void Armory_list_Initialize(Armory_list* pVal)
{
	(void)pVal;

    int i1;

	i1 = 0;
	while (i1< 3) {
	    Rocket_Initialize((&(pVal->arr[i1])));
	    i1 = i1 + 1;
	}
	pVal->nCount = 1;
}
void Armory_Initialize(Armory* pVal)
{
	(void)pVal;



	/*set info */
	ArmoryInfo_Initialize((&(pVal->info)));
	/*set count */
	pVal->count = 0;
	/*set list */
	pVal->exist.list = 1;
	Armory_list_Initialize((&(pVal->list)));
}

flag Armory_IsConstraintValid(const Armory* pVal, int* pErrCode)
{
    flag ret = TRUE;
    int i1;
	(void)pVal;
	
    ret = ArmoryInfo_IsConstraintValid((&(pVal->info)), pErrCode);
    if (ret) {
        if (pVal->exist.list) {
        	ret = ((1 <= pVal->list.nCount) && (pVal->list.nCount <= 3));
        	*pErrCode = ret ? 0 :  ERR_ARMORY_LIST; 
        	if (ret) {
        	    for(i1 = 0; ret && i1 < pVal->list.nCount; i1++) 
        	    {
        	    	ret = Rocket_IsConstraintValid((&(pVal->list.arr[i1])), pErrCode);
        	    }
        	}
        }
    }

	return ret;
}

